### ISSUE TITLE
Deleting Selected Task Breaks Site

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#100]
Using the task creator, start creating a task, select a tag, but don't finish creating the task.
Now go to settings and delete the tag you selected.
Close out of settings and the page crashes.

**Comment by mt-xing** [comment]
This is **not** fixed, despite the branch reference, as the flow type checker is having some issues on my machine. I'm still working on it.

**Comment by SamChou19815** [comment]
Should be fixed in #116.
