### ISSUE TITLE
CS 2110 vs ENGRD 2110

### ISSUE THREAD

**Issue by WilliamRockwellEvans** [cornell-dti/samwise#126]
**Describe the bug**

When importing CS 2110, the exams for ENGRD 2110 are also imported. (they're the same class, and it's an obvious bug)

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

**Environment (optional)**
 - OS: [e.g. macOS]

**Additional context (optional)**

**Comment by SamChou19815** [comment]
Fixed
