### ISSUE TITLE
Type Cursor is not visible on Windows over a task with default tag

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#149]
The default gray happens to be the exact same shade of gray as the default typing I-cursor in Windows. This means that if a user creates a task with default tag, pins it, and then in Focus view tries to hover over the "Add Subtask" field and type more text, their cursor seems to disappear.

**Comment by SamChou19815** [comment]
The designer suggests we can try #a6a6a6

**Comment by mt-xing** [comment]
Fixed.
