### ISSUE TITLE
Can't See Arrow in Future View when there are too many subtasks

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#169]
When there's subtasks behind the next arrow in future view, they kind of blend together and it's hard to click either one.

![{59095E95-A0E7-413D-8214-873EAFABA354}](https://user-images.githubusercontent.com/6147405/54169282-6e472080-4448-11e9-9c08-646e7adfe405.png)

**Comment by SamChou19815** [comment]
Designers: We can try to move the arrow to the right of all the cards in n-days view.
