### ISSUE TITLE
Tab Support

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#197]
Tabbing through the page is pretty broken

**Comment by SamChou19815** [comment]
#206 fixed the task creator issue with tabbing. However, these things still cannot be accessed by tabs:
- pin button
- close button
- checkbox
- view switcher
- settings button
- etc

**Comment by SamChou19815** [comment]
#201 is related

**Comment by SamChou19815** [comment]
Here is a design problem:
Suppose we make these changes:
<img width="694" alt="Screen Shot 2019-04-15 at 10 25 30 PM" src="https://user-images.githubusercontent.com/4290500/56177661-6b9e9480-5fcd-11e9-95b7-03a8941ef5c5.png">
We can instantly fix the problem of checkbox a11y in focus view (they will be reachable by tabbing control). However, it will destroy the convenience of tabbing between different subtasks. (With this change, you need two tabs. If we want to also support tabbing control of those buttons, the user needs even more tabs to switch between subtasks.)
