### ISSUE TITLE
Focusing an Overdue Task with Checked Subtask Crashes Site

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#227]
Have a task with at least one subtask. Focus the subtask and complete it, so that the card for the entire task shows up in your focus view's completed section (but the main task itself is neither checked nor focused). Let the due date pass, so that the main task becomes overdue. Now try to focus the main task. The site will crash.

![Crash Screen](https://user-images.githubusercontent.com/6147405/56237317-bebe2900-6059-11e9-8bd7-2275908f28d9.png)

**Comment by mt-xing** [comment]
This is on the staging site. Attempts to reproduce in production have not succeeded, thankfully.

**Comment by SamChou19815** [comment]
@mt-xing I hope the screenshot is obtained from local dev machine. Otherwise our build process is also buggy.

**Comment by mt-xing** [comment]
@SamChou19815 The screenshot is from local dev. The staging site still crashes - it just doesn't display the error log.

**Comment by SamChou19815** [comment]
@mt-xing I tried to edit one task in the database to make it overdue, but I was unable to reproduce the error.
![fine](https://user-images.githubusercontent.com/4290500/56243221-15cafa80-6068-11e9-990a-19b53f7c678b.gif)

**Comment by mt-xing** [comment]
@SamChou19815 Focus the overdue task, not check it.
