### ISSUE TITLE
Overlapping text in mobile settings page

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#304]
**Describe the bug**
There is some rather unusable overlapping text in settings on very narrow screens.

**To Reproduce**
Visit Settings on mobile

**Screenshots**
![image](https://user-images.githubusercontent.com/6147405/66259206-356fef80-e77c-11e9-8fa0-6b68a31fb19f.png)

**Comment by mt-xing** [comment]
Potential design fix: just get rid of the color names on very narrow screens; just keep the little color dot.

**Comment by AhsanAyaz** [comment]
@mt-xing could you kindly share any test credentials for logging in?
I don't want to create a Cornell account to be able to contribute 🙂 
You can email me at `ahsan.ubitian@gmail.com`

**Comment by SamChou19815** [comment]
@AhsanAyaz This is a client side only check performed here.
https://github.com/cornell-dti/samwise/blob/3eb7103062ef75c2842f7138f1bdc38b67d135fd/frontend/src/components/Util/AppInit/LoginBarrier.tsx#L49-L62
You can disable it to help you play with the code.
In terms of contribution, unfortunately, we decided to reserved these newly created `good first issue` tasks for our new developers. We are also in the process of setup CLA for all contributors and we may reach back once that's finished.

**Comment by ptwu** [comment]
Fixed in #316
