### ISSUE TITLE
Next and Previous Buttons from 4-Day Future View are Gone

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#317]
**Describe the bug**
The buttons are gone. There's no way to navigate future view without going into 2-week / month modes.

**To Reproduce**
Visit the staging site

**Screenshots**
![image](https://user-images.githubusercontent.com/6147405/66323867-7722a680-e8f2-11e9-95a0-dc374e8991ec.png)

**Environment (optional)**
Tested on Windows 10, latest Chrome

**Additional context (optional)**
Seems to be a regression from #302 
Blocking #315

**Comment by SamChou19815** [comment]
Fixed in #318.
