### ISSUE TITLE
Save button in future view editor can go off screen

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#327]
**Describe the bug**
A task with a lot of subtasks can push the save button off screen

**To Reproduce**
Make a task with a lot of subtasks. Open the task in future view. Edit something like the date. Try to click save.

**Screenshots**

Note that you can't even see the save button b/c it has been pushed off the bottom of the screen:

![image](https://user-images.githubusercontent.com/6147405/67096523-6aba0b80-f186-11e9-92d7-65adc4fa571b.png)

**Environment (optional)**
Windows 10, Chrome

**Comment by ptwu** [comment]
Fixed in #337
