### ISSUE TITLE
[work-plan] Canvas Integration

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#330]
- [x] ~~OAuth sign in (Sign in with Canvas button in Settings, sign out button after signed in) @pihucode~~
- [x] Store token in Firestore (`samwise-settings` table) - have a field to store Canvas token; null by default (not integrated), token exists <=> user is integrated with Canvas @pihucode 
- [x] Write script to fetch assignments @jason-tung 
- [x] Add assignments to calendar @jason-tung 
- [x] Edit task editor and display to disable editing for Canvas tasks @pihucode 
- [x] Fix timezone bug @jason-tung

**Comment by SamChou19815** [comment]
Mark as done since we decided not to support oauth for canvas
