### ISSUE TITLE
Overdue Repeating Tasks Don't Get Focused

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#333]
**Describe the bug**
Normally, when the due date of a task arrives, it is automatically focused. Thus, when the task becomes overdue, the task will be in your focus with the red exclamation mark.
However, when the due date of a non-forked instance of a repeating task arrives, nothing happens. If the due date passes, then the instance just disappears off your feed entirely.

Blocks #313 

**To Reproduce**
Create a repeating task where there is an instance tomorrow. Come back in 2 days. Note that nothing is in focus and there is no indication you had a task due yesterday.

**Comment by SamChou19815** [comment]
Blocked by #368
