### ISSUE TITLE
Tag Field in Task Editor Doesn't Look Clickable

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#339]
**Describe the bug**
Users don't realize that the tag name inside the task editor component can be clicked, leading to confusion about how to change the tag of a preexisting task.

**Screenshots**
The MATH 3320 field is clickable:
![image](https://user-images.githubusercontent.com/6147405/67640241-b92a8100-f8cf-11e9-99e8-1988cd9e255f.png)
But you have to hover over it to notice:
![image](https://user-images.githubusercontent.com/6147405/67640238-a617b100-f8cf-11e9-8321-067d5db30d3e.png)

**Comment by SamChou19815** [comment]
We lost all the designers and I'm not sure how we plan to do with this. Closing it unless we suddenly got some design.
