### ISSUE TITLE
New Task Editor Design

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#340]
Update `TaskEditor` to look like the designs on Zeplin

![image](https://user-images.githubusercontent.com/6147405/67640412-d6138400-f8d0-11e9-8f15-bbc600dc4242.png)

If a task repeats on one or two days, list the days it repeats. If there's 3 or more days a task repeats, just say "repeats x days a week" where x is the number of days.

Blocks #313

**Comment by SamChou19815** [comment]
Fixed in #357
