### ISSUE TITLE
Loading Screen Has Wrong Website

### ISSUE THREAD

**Issue by jason-tung** [cornell-dti/samwise#343]
**Describe the bug**
The Samwise loading screen has the wrong website in the URL bar! It says samwise.com; we are samwise.today!

**To Reproduce**
Open Samwise and watch the loading screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/33106747/67645959-09223b80-f902-11e9-9d09-4f19a8088c2f.png)

**Comment by ptwu** [comment]
also, is Samwise really a student planner "for everyone" 🤔?

**Comment by mt-xing** [comment]
> also, is Samwise really a student planner "for everyone" 🤔?

It isn't, but marketing hasn't given us anything better yet.
