### ISSUE TITLE
Lots of tasks on same date: calendar gets cut off

### ISSUE THREAD

**Issue by meganyin13** [cornell-dti/samwise#349]
**Describe the bug**
When you have a lot of tasks on one date, if you try to click calendar on last task, it gets cut off.

**To Reproduce**
Create many tasks on same date such that it overfills vertical width. On the last one, open calendar, it is cut off.

**Screenshots**
Calendar gets cut off here:
![image](https://user-images.githubusercontent.com/20008134/68093298-24d99480-fe62-11e9-9584-52cd1cb9f9a1.png)

**Environment (optional)**
 - Browser Chrome
 - OS: macOS

**Additional context (optional)**

**Comment by SamChou19815** [comment]
Fixed in #356
