### ISSUE TITLE
Can't Check Unsaved Subtask

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#354]
**Describe the bug**
Neither of the task editors (in focus view or in future view) allow you to check off a newly created subtask. You have to create the subtask first, then click save, and then try to check it before it will work.

**To Reproduce**
Create a new task. Open it in an editor. Type a new subtask, then, without clicking save, try to check the check box. Nothing happens.

**Environment**
Happens both in staging and on production.
Tested on Chrome, Windows 10, latest version.

**Comment by SamChou19815** [comment]
Might be a regression introduced in #309.
