### ISSUE TITLE
Half of app disappears at 840px

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#389]
**Describe the bug**
At a width of exactly 840 px, the future view disappears but focus view doesn't expand to fill the space

**To Reproduce**
Make the window 840px wide.

**Screenshots**

![2Untitled](https://user-images.githubusercontent.com/6147405/70873721-eebd2380-1f7c-11ea-93ac-ac194907ab33.png)

**Comment by SamChou19815** [comment]
This is really unfortunate. Only 840px breaks it.

**Comment by SamChou19815** [comment]
These are probably some problematic code:
https://github.com/cornell-dti/samwise/search?q=840&unscoped_q=840

**Comment by meganyin13** [comment]
At 840px do we want Focus View to expand and fill the page or for it to be a split between Focus and Future View?
