### ISSUE TITLE
API keys exposed in code

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#39]
https://github.com/cornell-dti/samwise/blob/2fe5b64d3539fe91f69e6d6ede05929d1cad0a93/backend/app/auth.py#L12

**Comment by SamChou19815** [comment]
This is not a problem. [Firebase API Key is designed to be public](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public). We only need to ensure that our **firebase admin** API key is not exposed.
