### ISSUE TITLE
Future view calendar edit is broken

### ISSUE THREAD

**Issue by jason-tung** [cornell-dti/samwise#400]
**Describe the bug**
The calendar when a user edits their tasks in future view does not display fully and it is not possible to scroll to see it. 

**To Reproduce**
Edit any non-repeating task in month future view.

**Screenshots**
![image](https://user-images.githubusercontent.com/33106747/73317502-4c8f8d00-4204-11ea-9316-6ecb83d83efa.png)

**Comment by mt-xing** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/6147405/73459983-b9f70700-4345-11ea-934a-930f3d4710f5.png)

**Comment by jason-tung** [comment]
edited-- must be in month view rather than 2 week

**Comment by mt-xing** [comment]
Still cannot reproduce

![image](https://user-images.githubusercontent.com/6147405/73600853-84f4db00-4524-11ea-8ddf-78124b7b43f9.png)

**Comment by SamChou19815** [comment]
The date has to be in the lower half of the 2W/monthly view
<img width="1191" alt="Screen Shot 2020-05-05 at 16 38 59" src="https://user-images.githubusercontent.com/4290500/81113920-f7dc6c00-8eee-11ea-90a5-b29dca120ada.png">

**Comment by SamChou19815** [comment]
This regression is introduced in #337. Under the current setup, scrollable editor and calendar display since to be excluding each other. Changing `overflow-y: visible` fixes this bug, but will break scroll again. 😢
