### ISSUE TITLE
Repeating task "Stops" radio button QOL

### ISSUE THREAD

**Issue by jason-tung** [cornell-dti/samwise#401]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Editing either the stops on date or after x weeks fields should automatically swap the radio button to that selection. 
e.g. the default selection is stop on today, but if I edit the stops after x weeks button to be stops after 2 weeks, the radio selection should switch to stop on rather than remain on "stop on today". 

I believe this is a reasonable feature because users who forget to click to swap the radio button after editing the "stop after x weeks" field will be confused when the task doesn't appear on their calendar.

**Comment by mt-xing** [comment]
Editing the Stops on Date already jumps the radio button to that selection on staging.

**Comment by SamChou19815** [comment]
> Editing the Stops on Date already jumps the radio button to that selection on staging.

This might be windows only behavior.
