### ISSUE TITLE
Subtasks out of order for more than 8 subtasks on one main task

### ISSUE THREAD

**Issue by meganyin13** [cornell-dti/samwise#431]
**Describe the bug**
When you add more than 8 subtasks to a main task in an order, that order isn't preserved in TaskEditor. This is an issue in staging and production.

**To Reproduce**
Add more than 8 subtasks to the same main task in a specific order (number the subtasks). Open the TaskEditor. Notice the subtasks are in a different order.

**Screenshots**
![image](https://user-images.githubusercontent.com/20008134/75629661-c9ba7300-5bb1-11ea-91a0-ac3d19749303.png)

**Environment (optional)**
 - Browser: Chrome
 - OS: macOS

**Additional context (optional)**

**Comment by SamChou19815** [comment]
I remember having issue like that from time to time. I don't think the number 8 is significant here. It's probably due to timing of typing unfortunately intertwined with timing of auto syncing.

**Comment by meganyin13** [comment]
The ordering works fine for <= 8 subtasks, but at more than 8 subtasks the subtasks show up out of order. Also when adding more than 8 subtasks in floating TaskEditor, the order jumps in the middle of typing.

**Comment by SamChou19815** [comment]
I think this one should be resolved during the SubTask -> Task migration, when we uncovered some bad race conditions. Closing this unless we found another repro.
