### ISSUE TITLE
Make course-info script fetch FA20 final info when Cornell releases it

### ISSUE THREAD

**Issue by SamChou19815** [cornell-dti/samwise#510]

**Comment by ptwu** [comment]
It looks like prelim exams but not finals are posted on the registrar (https://registrar.cornell.edu/exams/fall-prelim-exam-schedule). Is there a way to import the prelim info even while we still don't have the final info?

**Comment by SamChou19815** [comment]
> It looks like prelim exams but not finals are posted on the registrar (https://registrar.cornell.edu/exams/fall-prelim-exam-schedule). Is there a way to import the prelim info even while we still don't have the final info?

Yes, you can potentially fix the html parsing in https://github.com/cornell-dti/samwise/blob/master/course-info/src/fetch-exam.ts and then uncomment prefix processing code in https://github.com/cornell-dti/samwise/blob/master/course-info/src/merge-json.ts#L64-L66

**Comment by SamChou19815** [comment]
Reopen since final exams are not there yet :(

**Comment by ptwu** [comment]
[Looks like this issue is fixable now](https://registrar.cornell.edu/exams/fall-final-exam-schedule). Let's get a patch for final times in the work sesh tomorrow (and they changed the date formats **again**)
