### ISSUE TITLE
Exam importing does not include essay due dates.

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/samwise#53]
Cornell posts the final essay/project due dates along with final exam dates. It would be helpful if these were included in the import feature.

**Comment by SamChou19815** [comment]
@rockon999  
Unfortunately, the information Cornell posted [here](https://registrar.cornell.edu/exams/spring-final-exam-schedule) are not specific enough. We cannot automatically decide whether each class has a final project, so we cannot use the information correctly and effectively at the end of the long list.
Right now, we do not have enough resources to manually investigate and label each class, so I will put this in a backlog.

**Comment by SamChou19815** [comment]
Please reopen the issue when there are better data sources available.
