### ISSUE TITLE
Focus checkboxes are broken.

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/samwise#54]
Checkboxes are broken in the focus bar. Specifically, when unchecked they render 0x0 and when checked they "break" outside their bounds. I believe you might be wrapping them in a div that doesn't support them.

![nocheck](https://user-images.githubusercontent.com/2943271/52368095-9c85aa80-2a1b-11e9-8538-07e2aab8fb40.png)
![checkwrong](https://user-images.githubusercontent.com/2943271/52368099-a0193180-2a1b-11e9-943d-5d9c77a85486.png)

**Comment by mt-xing** [comment]
Should be fixed now
