### ISSUE TITLE
The bottom bar scrolls with the content, should probably be fixed.

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/samwise#56]
The bottom bar isn't fixed so it scrolls with content (esp. when the focus bar gets very high) *and* when their is too little content is appears with a huge white gap between it and the bottom.

![bottom-bar-isnt-fixed](https://user-images.githubusercontent.com/2943271/52368250-fab28d80-2a1b-11e9-926e-f48defba00ad.png)
![scrolling the focus bar should be independent of the rest of the view](https://user-images.githubusercontent.com/2943271/52368283-0bfb9a00-2a1c-11e9-9f32-9963ea2f3bf4.png)

**Comment by SamChou19815** [comment]
It should be fixed in #95.
