### ISSUE TITLE
[group-task] Making many groups overflows the SideBar

### ISSUE THREAD

**Issue by ptwu** [cornell-dti/samwise#585]
**Describe the bug**
If you make a lot of groups, each group icon gets rendered below the previous one, and causes the New Group button to move down. Making many of them may cause the New Group button to become inaccessible.

**To Reproduce**
Keep making groups (you can have more than one group for a class). On my screen, when I have more than 5, the New Group button clips the settings button.

**Screenshots**
![image](https://user-images.githubusercontent.com/7517829/96062503-d8654a00-0e63-11eb-9d83-5e0fa3d8dddc.png)

**Comment by jason-tung** [comment]
How should we resolve this from a design perspective? Make the div scrollable?
