### ISSUE TITLE
No symbol to tell that the button is for removing a tag while registering

### ISSUE THREAD

**Issue by dhruvbaijal** [cornell-dti/samwise#59]
Circled part of image below:

<img width="1076" alt="screen shot 2019-02-09 at 10 58 14 am" src="https://user-images.githubusercontent.com/8575406/52522939-af85be00-2c59-11e9-80b0-dcfdaf7d2f0a.png">

**Comment by mt-xing** [comment]
This is a Safari problem. It definitely shows up in Chrome. We'll look into it.

**Comment by dhruvbaijal** [comment]
I found this error while using Chrome.

**Comment by mt-xing** [comment]
Should be fixed now.
