### ISSUE TITLE
Mobile Focus View Button

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#63]
In mobile view, the z-index on the focus view icon is messed up, so that if I scroll the page to where it overlaps with the progress bar, the progress bar blocks pointer events to the button.

![image](https://user-images.githubusercontent.com/6147405/52524032-48223b00-2c66-11e9-8b70-9a8a070d18da.png)

**Comment by SamChou19815** [comment]
Fixed in #95.
