### ISSUE TITLE
Assigning Group Add Date squashed

### ISSUE THREAD

**Issue by jason-tung** [cornell-dti/samwise#663]
**Describe the bug**
If your browser window is too small (~1250px) the add date on assigning group tasks becomes very hard to read.

**To Reproduce**
Make your browser window smaller

**Screenshots**
![image](https://user-images.githubusercontent.com/33106747/99889003-41886c00-2c1f-11eb-9560-3cee20b4c8d8.png)

**Comment by SamChou19815** [comment]
I think it is fixed by Pi's #671.
