### ISSUE TITLE
Subtasks Randomly Disappear

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#679]
**Describe the bug**
Performing common operations will cause subtasks to disappear.

**To Reproduce**
Create a new task due tomorrow. Do not pin the main task to focus.
Create two subtasks for the task. Pin only the first subtask to focus; do not pin the second.
Check off the first subtask.
Observe that the second subtask will disappear.

**Environment (optional)**
Production
Windows 10, Google Chrome (latest updates on both)

**Comment by SamChou19815** [comment]
![129692493_423300008716220_5044317792053410624_n](https://user-images.githubusercontent.com/4290500/101307783-43a11c00-3816-11eb-8983-beb1bb7bb01f.png)

@mt-xing I did find a repo but I think it somehow makes sense. You can argue that the second subtask is never part of focus view. Although whether this argument makes sense is another question.

**Comment by mt-xing** [comment]
@SamChou19815 when you check off the first subtask, the second subtask gets deleted

**Comment by SamChou19815** [comment]
> @SamChou19815 when you check off the first subtask, the second subtask gets deleted. This is a data deletion issue.

I'm not sure whether we are talking about the same thing. But if you see my screenshot the second one is still there.

**Comment by mt-xing** [comment]
@SamChou19815 You need to check off the pinned subtask and when you do, the second one is deleted for no reason

Before:
![image](https://user-images.githubusercontent.com/6147405/101407235-95928200-38a8-11eb-96ae-98cc3f10ae0e.png)

After:
![image](https://user-images.githubusercontent.com/6147405/101407256-9cb99000-38a8-11eb-8939-8f60249ab77d.png)

Upon further testing, it only happens if you check the subtask from focus view, not from future view.

**Comment by SamChou19815** [comment]
> @SamChou19815 You need to check off the pinned subtask and when you do, the second one is deleted for no reason
> 
> Before:
> ![image](https://user-images.githubusercontent.com/6147405/101407235-95928200-38a8-11eb-96ae-98cc3f10ae0e.png)
> 
> After:
> ![image](https://user-images.githubusercontent.com/6147405/101407256-9cb99000-38a8-11eb-8939-8f60249ab77d.png)
> 
> Upon further testing, it only happens if you check the subtask from focus view, not from future view.

Thanks for the repro. This is a big SEV :(

**Comment by SamChou19815** [comment]
Note: this is a result of the migration of subtask -> task.

In this migration, subtasks are now part of the task. In the editor in the focus view, it's editing on a filtered task. Since subtask are no longer part of a task, we removed the subtask specific diffing. Therefore, on edit, it will mistakenly replace the entire task with the filtered task. Therefore, the subtask that's not part of the focus view got dropped.

**Comment by ptwu** [comment]
@mt-xing fix should be in prod now. thanks for reporting!
