### ISSUE TITLE
Inconsistency in naming props

### ISSUE THREAD

**Issue by JBoss925** [cornell-dti/samwise#68]
[For DevSesh 11]

I noticed in some classes like [TaskView.jsx](https://github.com/cornell-dti/samwise/blob/master/frontend/src/components/TaskView/TaskView.jsx) you just say Props and State when declaring (which is a bit unspecific), but then sometimes you name the Props struct something different like in [ProgressIndicator.jsx](https://github.com/cornell-dti/samwise/blob/master/frontend/src/components/ProgressTracker/ProgressIndicator.jsx). I prefer the second way, but it was just something I noticed.

**Comment by SamChou19815** [comment]
The naming inconsistency is caused by React & JS syntax itself. You can easily use the object destruct syntax in function components but you cannot have similar syntax for class components.
