### ISSUE TITLE
Allow color change for tasks not associated with a class

### ISSUE THREAD

**Issue by liam0215** [cornell-dti/samwise#743]
**Is your feature request related to a problem? Please describe.**
I have a lot of non-class related tasks and it looks really monochrome cuz I can't change the color. 

**Describe the solution you'd like**
Either different options for the color associated with None or the ability to change color at an individual task level without changing class association.

**Describe alternatives you've considered**
Haven't considered any alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/8989334/113511334-5a8a1d80-952d-11eb-8e6c-23e7f0edc8d6.png)

**Comment by SamChou19815** [comment]
You can go to settings and add other tags like shown in this screenshot:

<img width="1506" alt="Screen Shot 2021-04-04 at 14 03 17" src="https://user-images.githubusercontent.com/4290500/113517540-8a95e880-954e-11eb-8122-c90b5aec3c74.png">

**Comment by liam0215** [comment]
Thank you :)
