### ISSUE TITLE
Checkbox collapses for subtasks in focus view

### ISSUE THREAD

**Issue by me382** [cornell-dti/samwise#86]
![collapsed checkbox](https://user-images.githubusercontent.com/32252696/52538542-f818a680-2d41-11e9-810d-dba6f6436369.PNG)
![collapsed checkbox fix-ish](https://user-images.githubusercontent.com/32252696/52538543-f818a680-2d41-11e9-9484-73fa6544206c.PNG)

**Comment by mt-xing** [comment]
Should be fixed now
