### ISSUE TITLE
Deformed checkbox for overdue task in focus view

### ISSUE THREAD

**Issue by SamChou19815** [cornell-dti/samwise#91]
**To Reproduce**
Simply have an overdue task in focus view.

**Expected behavior**

**Screenshots**
<img width="251" alt="screen shot 2019-02-11 at 1 17 29 pm" src="https://user-images.githubusercontent.com/4290500/52584277-99b1fd80-2dff-11e9-8eea-f77199b69e73.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Latest

**Comment by mt-xing** [comment]
Should be fixed now
