### ISSUE TITLE
Page Still Scrolls Vertically

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#99]
Even with the new focus bar that scrolls independently, there's still a scroll on the entire page. That shouldn't happen.

![image](https://user-images.githubusercontent.com/6147405/52874113-a8a9f000-311e-11e9-9b73-fc7b8f723b72.png)

**Comment by mt-xing** [comment]
https://github.com/cornell-dti/samwise/commit/935c130e9805e39af93717ba85b4dc31d4b0a920

**Comment by SamChou19815** [comment]
Should be fixed by #106.
